### ISSUE TITLE
Policy error when extending User model.

### ISSUE THREAD

**Issue by crumb1e** [kirschbaum-development/nova-mail#26]
I'm extending my User already, so I am unable to extend the `Illuminate\Foundation\Auth\User` model in order for the `NovaSentMailPolicy` to work. 

Results in the following error when accessing the nova admin:
```php
Argument 1 passed to KirschbaumDevelopment\NovaMail\Policies\NovaSentMailPolicy::create()
must be an instance of Illuminate\Foundation\Auth\User, instance of App\User given.
```

Looks like this was changed in PR #17, not sure what a good workaround would be, maybe a config value for the User model?

**Comment by crumb1e** [comment]
Just incase anyone else comes across this, as a workaround for now, I have extended the `SentMailPolicy` and added it into my `AuthServiceProvider`.

**Comment by brandonferens** [comment]
@crumb1e This really is a good point. I'm assuming that your user is still implementing `Illuminate\Contracts\Auth\Authenticatable` which is the contract necessary for being logged in. Perhaps the code committed in PR #17 should be altered to resolve the `$user` model from that contract instead. Do you think that would solve the issue?

**Comment by adammparker** [comment]
Solved in the latest release, thanks!

https://github.com/kirschbaum-development/nova-mail/releases/tag/1.0.2
