### ISSUE TITLE
Illegal string offset 'id' when trying to run send action without template

### ISSUE THREAD

**Issue by n1kio** [kirschbaum-development/nova-mail#32]
When I try to run the action with mail content from scratch and without selecting a template I get the following error.
```
Illegal string offset 'id'
```

![illegal-offset](https://user-images.githubusercontent.com/36363733/86765630-b0d33a00-c049-11ea-9464-46ea2587d8bc.png)

When I select a template it works just fine.

Any ideas how to fix this?

**Comment by nickbluestone98** [comment]
I got around the issue by making a plain text template. Looks to be an undefined id for the template declaration.

**Comment by abderrahmane-mhd** [comment]
Same problem here.

**Comment by cbrinicombe13** [comment]
Same problem here when will this be resolved?

**Comment by adammparker** [comment]
Solved with the latest release - https://github.com/kirschbaum-development/nova-mail/releases/tag/1.0.2

Thanks!
