### ISSUE TITLE
Issue for existing application with observer for model with mailable trait

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [kirschbaum-development/nova-mail#36]
When running a fresh database migration (i.e. for unit testing) or an upgrade from v0.1.0 to v1.0.0 on an existing application with an observer on a model with the mailable trait, it is not possible to run the migration command, it throws an error:
"no such table: nova_mail_templates".

So I guess the boot of the Mailable trait runs already when booting an application with observers and directly throwing this error, preventing to proceed with the migrate.

**Comment by LorenzoSapora** [comment]
Hitting this too. Temporary solution is to comment out the `use Mailable;`, and run migration, then uncomment. You could also use the new database schema squash to generate the SQL (`php artisan schema:dump --prune`).

**Comment by pktharindu** [comment]
This also causes failure for the test cases, with a query exception: 

```
Base table or view not found: 1146 Table 'test_db.nova_mail_templates' doesn't exist
```

**Comment by adammparker** [comment]
Sorry for the delay here folks, just pushed out a new release! 👍
