### ISSUE TITLE
Laravel.log - Could not bind NovaMailEvents

### ISSUE THREAD

**Issue by juliangeissler** [kirschbaum-development/nova-mail#51]
Hello,

our laravel.log gets filled with the following error

`Could not bind NovaMailEvents. NovaMail tables might not have migrated yet, typical when running fresh migrations during testing or local development.`

We already use the newest package version, 1.0.4 and there are no missing migrations

In the nova_mail.php config we didnt enable `nova_mail_event` under `show_resources` or set `eventables`

Is there a way to disable that error? Especially when we dont use the resource

Our current config
```
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Mail Template Disk
    |--------------------------------------------------------------------------
    |
    | You can specify the disk (from config/filesystems.php) that you'd like
    | temporary email files used by the SendMail mailable to be created.
    |
    */

    'compiled_mail_disk' => 'local',

    /*
    |--------------------------------------------------------------------------
    | Mail Template Path
    |--------------------------------------------------------------------------
    |
    | You can specify the path that you'd like temporary email
    | files used by the SendMail mailable to be created.
    |
    */

    'compiled_mail_path' => 'views/emails',

    /*
    |--------------------------------------------------------------------------
    | Show Resources
    |--------------------------------------------------------------------------
    |
    | This deterimines if the provided Nova resources
    | are displayed in the Nova navigation menu.
    |
    */
    'show_resources' => [
        'nova_sent_mail' => true,
        'nova_mail_template' => true,
    ],
];
```

**Comment by adammparker** [comment]
@juliangeissler That's fine if you don't define those. It just means there won't be any models available in the dropdown when editing a template.

I'm trying to think of what else could cause that error. If you don't have any events at all in that table then the query should never iterate in that Mailable trait, that's really the only opportunity for an error I believe.

**Comment by adammparker** [comment]
Closing this for now, let me know if you are still having this issue.
