### ISSUE TITLE
Problema al crear un envío individual

### ISSUE THREAD

**Issue by pedami** [kirschbaum-development/nova-mail#56]
Hola, adjunto captura del error que me está arrojando al programar un envío individual.
Gracias.

![image](https://user-images.githubusercontent.com/6138775/184451155-6ad6bfba-9a95-41f0-884c-7bf16e04620c.png)

**Comment by adammparker** [comment]
Hello, @pedami - were you able to sort this out? I can't really tell much from the error message, you'd probably need to include the full stack trace from the error log.

**Comment by adammparker** [comment]
Closing this one out, let me know if you still need help and can answer my questions above.
