### ISSUE TITLE
Request for Update: Support for Latest Version of Laravel Nova

### ISSUE THREAD

**Issue by jahmoh82** [kirschbaum-development/nova-mail#62]
Are there any plans to support the latest version of Laravel Nova? I've encountered issues where templates aren't loading properly, resulting in a '404 Not Found' error when attempting to send manual emails. Additionally, errors related to subjects and CC are occurring. There also seems to be an issue with event triggering when certain actions are performed. Any contributions or guidance on how to address these issues and expedite the update process would be greatly appreciated.

![image](https://github.com/kirschbaum-development/nova-mail/assets/13553403/9b412a07-48f9-403f-9412-7be611443587)
<img width="1026" alt="image" src="https://github.com/kirschbaum-development/nova-mail/assets/13553403/44f58c2f-f6bb-4940-9fce-3483674aad13">
![image](https://github.com/kirschbaum-development/nova-mail/assets/13553403/9c42c36f-b4df-418f-95db-862242cc2fc4)

**Comment by luisdalmolin** [comment]
This package supports Nova 4, so this should work. Try to make sure the package is registered and no routes are overriding the package routes.

Otherwise, please submit a repo replicating the issue so we can understand what's going on.

**Comment by jahmoh82** [comment]
@luisdalmolin - Thank you so much! I've reinstalled it, and it appears to be functioning perfectly now. Much appreciated!
